### ISSUE TITLE
yarn add btcmarkets-node-sdk

### ISSUE THREAD

**Issue by shortthefomo** [BTCMarkets/btcmarkets-node-sdk#12]
<img width="1215" alt="Screen Shot 2021-04-26 at 21 08 40" src="https://user-images.githubusercontent.com/508629/116169874-a7e44f80-a6d3-11eb-8892-7b80b927f9d6.png">

Here is how i was trying to use it in pattern.
`var self = null
var globalIsWebSocketOpen = false

const BTCMarkets = require('btcmarkets-node-sdk').default;
const client = new BTCMarkets();

module.exports = class btcmarkets {
  constructor() 
  {
    self = this
  }

  //open websocket connection
  openWebSocket(pubSubManager, stable) 
  { 
    const socket = client.socket;
      
    socket.subscribe({
      marketIds: ['XRP-AUD'],
      channels: ['heartbeat', 'trade'],
    });

    console.log('Btcmarkets subscribed to: XRPAUD')
    console.log("Connected to Btcmarkets! :)")
..
..
..
..
`

**Comment by cipiripper** [comment]
@lathanbritz Hi there, the issue has been fixed now. Please install the latest version of `btcmarkets-node-sdk`.
