### ISSUE TITLE
Issues installing this package

### ISSUE THREAD

**Issue by choliveira** [BTCMarkets/btcmarkets-node-sdk#13]
Hi,
 
I am trying to test this sdk and as per documentation I run `yarn add btcmarkets-node-sdk` in my code base to install it, all good during the installation, but when I try to run my code I get this error:
```
Error: Cannot find module '/Users/carlosholiveira/my-codei/node_modules/btcmarkets-node-sdk/dist/index.js'. Please verify that the package.json has a valid "main" entry
```
Please see screenshot attached with the error.

When I looked in my `node_module/` folder I can see the folder btcmarkets-node-sdk but it only has the package.json and the README.md files.

![Screen Shot 2021-05-04 at 5 23 11 pm](https://user-images.githubusercontent.com/9526236/116972966-260dab00-acff-11eb-87eb-6cc5b657ab32.png)
![Screen Shot 2021-05-04 at 5 30 20 pm](https://user-images.githubusercontent.com/9526236/116972974-29a13200-acff-11eb-9c8b-a947577ef552.png)

**Comment by cipiripper** [comment]
@choliveira Hi there, the issue has been fixed now. Please install the latest version of `btcmarkets-node-sdk`.

Closing the issue.
